name: 'Generic dependency submission'
description: 'Dependency submission parser for different dependencies sources.'
inputs:
  token:
    description: "GitHub Personal Access Token (PAT). Defaults to PAT provided by Action runner"
    required: false
    default: ${{ github.token }}
  language:
    description: "Programming language (e.g: java, python, javascript)"
    required: true
  dependency-management:
    description: "Dependency management used (maven, gradle, pip, npm etc)"
    required: true
  manifest-files:
    description: "List of files which should be parsed"
    required: true
runs:
  using: 'node16'
  main: 'action-dist/index.js'
